name: LetsTrack
options:
  bundleIdPrefix: com.tltmzmaos
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "2.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "5.9"
    GENERATE_INFOPLIST_FILE: YES
    INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
    INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
    INFOPLIST_KEY_UILaunchScreen_Generation: YES
    INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    INFOPLIST_KEY_CFBundleDisplayName: "Let's Track"
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    ENABLE_PREVIEWS: YES

targets:
  LetsTrack:
    type: application
    platform: iOS
    sources:
      - path: Application
      - path: Domain
      - path: Data
      - path: Presentation
      - path: Infrastructure
      - path: Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.tltmzmaos.letstrack
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.finance"
        INFOPLIST_KEY_NSCameraUsageDescription: "Camera access is needed to take photos of receipts"
        INFOPLIST_KEY_NSPhotoLibraryUsageDescription: "Photo library access is needed to select receipt images"
        INFOPLIST_KEY_NSFaceIDUsageDescription: "Face ID is used to protect your financial data"
        INFOPLIST_KEY_NSMicrophoneUsageDescription: "Microphone access is needed for voice transaction entry"
        INFOPLIST_KEY_NSSpeechRecognitionUsageDescription: "Speech recognition is used to convert your voice to transaction details"
        INFOPLIST_KEY_NSLocationWhenInUseUsageDescription: "Location access is used to record where you made transactions"
    dependencies:
      - target: LetsTrackWidget
        embed: true

  LetsTrackWidget:
    type: app-extension
    platform: iOS
    sources:
      - path: Widget
        excludes:
          - Info.plist
      - path: Presentation/Common/Extensions
      - path: Domain/Models
    info:
      path: Widget/Info.plist
      properties:
        CFBundleDisplayName: "Let's Track Widget"
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.tltmzmaos.letstrack.widget
        SKIP_INSTALL: YES
        ASSETCATALOG_COMPILER_WIDGET_BACKGROUND_COLOR_NAME: WidgetBackground
        ASSETCATALOG_COMPILER_APPICON_NAME: ""
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: ""

  LetsTrackTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: LetsTrack
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.tltmzmaos.letstrack.tests
        GENERATE_INFOPLIST_FILE: YES

schemes:
  LetsTrack:
    build:
      targets:
        LetsTrack: all
        LetsTrackTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - LetsTrackTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
